site_name: LazyWorld Wiki
site_url: null
site_description: LazyWrold Wiki
site_author: zhl
repo_name: Github
repo_url: https://github.com/lzwmc/lzwwiki
edit_uri: 'http://127.0.0.1:8000/edit-landing/?ref='
copyright: "Copyright © 2019 - 2023 LazyWorld"

extra:
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'

theme:
  name: material
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true

  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'

  favicon: 'assets/images/favicon.png'

  language: 'zh'

nav:
  - 简介:
    - Getting Started: index.md
  - 对于新玩家:
    - 成为此服务器的玩家: forplayer/fist.md
    - 服务器章程: forplayer/rulus.md
    - 游戏内指令指南: forplayer/cmdhepler.md
  - 对于服务器管理者:
    - 注意事项: foradmin/waringtings.md
    - 管理权限指南: foradmin/admincmd.md
  - 对于服务器运营者:
    - 服务器文件结构: forsuperadmin/theserver.md
    - 服务器网络结构: forsuperadmin/theinternet.md
  - 关于本文档的编写:
    - 关于: about/about.md
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
